# Generated by Django 2.1.5 on 2019-01-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followersmodel',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
    ]
