# Generated by Django 2.1.5 on 2019-02-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_referral_referralcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReferralCode',
        ),
    ]
