# Generated by Django 2.1.5 on 2019-01-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threadedcomments', '0003_threadedcomment_newest_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomThreadedComment',
            fields=[
                ('threadedcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threadedcomments.ThreadedComment')),
            ],
            options={
                'permissions': [('can_moderate', 'Can moderate comments')],
                'verbose_name': 'comment',
                'abstract': False,
                'verbose_name_plural': 'comments',
                'ordering': ('submit_date',),
            },
            bases=('threadedcomments.threadedcomment',),
        ),
    ]
