# Generated by Django 2.1.4 on 2019-01-06 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='comment_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='comment_replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='userName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commentreplies',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='comments.commentsModel'),
        ),
        migrations.AddField(
            model_name='commentreplies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
