# Generated by Django 2.1.5 on 2019-01-30 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadedcomments', '0003_threadedcomment_newest_activity'),
        ('comments', '0003_commentld'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentLDinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('LDcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_comment', to='threadedcomments.ThreadedComment')),
                ('LDuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentld',
            name='LDcomment',
        ),
        migrations.RemoveField(
            model_name='commentld',
            name='LDuser',
        ),
        migrations.RemoveField(
            model_name='commentld',
            name='threadedcomment_ptr',
        ),
        migrations.DeleteModel(
            name='commentLD',
        ),
    ]
