# Generated by Django 2.1.5 on 2019-02-01 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20190130_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentldinfo',
            name='LDcomment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_comment', to='comments.CustomThreadedComment'),
        ),
    ]
