# Generated by Django 2.1.5 on 2019-02-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20190201_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentldinfo',
            name='smoke_liked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentldinfo',
            name='steem_liked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentldinfo',
            name='whaleshare_liked',
            field=models.IntegerField(default=0),
        ),
    ]
