# Generated by Django 2.1.5 on 2019-02-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20190201_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentldinfo',
            name='smoke_liked',
        ),
        migrations.RemoveField(
            model_name='commentldinfo',
            name='steem_liked',
        ),
        migrations.RemoveField(
            model_name='commentldinfo',
            name='whaleshare_liked',
        ),
        migrations.AddField(
            model_name='commentldinfo',
            name='smoke_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentldinfo',
            name='smoke_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentldinfo',
            name='steem_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentldinfo',
            name='steem_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentldinfo',
            name='whaleshare_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentldinfo',
            name='whaleshare_like',
            field=models.BooleanField(default=False),
        ),
    ]
