# Generated by Django 2.1.5 on 2019-02-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20190202_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='memo',
            field=models.CharField(default='950f59db98164652', max_length=255),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
