# Generated by Django 2.1.5 on 2019-02-03 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20190203_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='curr_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='expired',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='memo',
            field=models.CharField(default='adcbd832ef9e40f3', max_length=255),
        ),
    ]
