# Generated by Django 2.1.5 on 2019-02-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_auto_20190203_1529'),
        ('advertisement', '0008_auto_20190203_1500'),
    ]

    operations = [
    ]
