# Generated by Django 2.1.5 on 2019-02-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_merge_20190204_0603'),
        ('advertisement', '0009_merge_20190204_0556'),
    ]

    operations = [
    ]
