# Generated by Django 2.1.5 on 2019-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bitshare',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
