# Generated by Django 2.1.4 on 2018-12-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_channel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.CharField(blank=True, default='false', max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='steem',
            field=models.CharField(blank=True, default='false', max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='whaleshare',
            field=models.CharField(blank=True, default='false', max_length=1024),
        ),
    ]
