# Generated by Django 2.1.4 on 2018-12-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20181225_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smoke_name',
            field=models.CharField(blank=True, default='false', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='steem_name',
            field=models.CharField(blank=True, default='false', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='whaleshare_name',
            field=models.CharField(blank=True, default='false', max_length=256),
        ),
    ]
