# Generated by Django 2.1.5 on 2019-01-13 05:22

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=upload.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='SmokeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permlink', models.CharField(blank=True, max_length=1024)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('post_url', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SteemVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permlink', models.CharField(blank=True, max_length=1024)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('post_url', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('thumbsUp', models.IntegerField(default=0)),
                ('thumbsDown', models.IntegerField(default=0)),
                ('thumbNail', models.CharField(max_length=512)),
                ('video', django.contrib.postgres.fields.jsonb.JSONField()),
                ('duration', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[(1, 'English'), (2, 'Chinese'), (3, 'Spanish'), (4, 'German')], default='1', max_length=20)),
                ('smoke', models.FloatField(default=0.0)),
                ('steem', models.FloatField(default=0.0)),
                ('whaleshares', models.FloatField(default=0.0)),
                ('total_earning', models.FloatField(default=0.0)),
                ('valuation', models.CharField(max_length=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('name', models.CharField(default='An apple a day keeps the doctor away', max_length=255)),
                ('publish', models.BooleanField(default=False)),
                ('monetize', models.BooleanField(default=False)),
                ('nsfw', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhaleShareVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permlink', models.CharField(blank=True, max_length=1024)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('post_url', models.CharField(blank=True, max_length=1024)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whaleVideos', to='upload.Video')),
            ],
        ),
        migrations.AddField(
            model_name='steemvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steemVideos', to='upload.Video'),
        ),
        migrations.AddField(
            model_name='smokevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smokeVideos', to='upload.Video'),
        ),
    ]
