# Generated by Django 2.1.1 on 2018-11-06 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('thumbsUp', models.IntegerField(default=0)),
                ('thumbsDown', models.IntegerField(default=0)),
                ('thumbNail', models.CharField(max_length=512)),
                ('video', models.CharField(max_length=512)),
                ('duration', models.CharField(max_length=10)),
                ('smoke', models.DecimalField(decimal_places=3, max_digits=10)),
                ('steem', models.DecimalField(decimal_places=3, max_digits=10)),
                ('whaleshares', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valuation', models.DecimalField(decimal_places=3, max_digits=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('video',),
            },
        ),
    ]
