# Generated by Django 2.1.5 on 2019-02-04 06:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
