# Generated by Django 2.1.5 on 2019-01-14 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='old_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='old_views_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
