# Generated by Django 2.1.1 on 2018-11-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='smoke',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='steem',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='valuation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='whaleshares',
            field=models.CharField(max_length=10),
        ),
    ]
