# Generated by Django 2.1.1 on 2018-11-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20181106_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='email',
            new_name='user_id',
        ),
    ]
