# Generated by Django 2.1.5 on 2019-02-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190204_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='uploaded', max_length=10),
        ),
    ]
