# Generated by Django 2.1.4 on 2019-01-07 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
