# Generated by Django 2.1.5 on 2019-01-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190114_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='video',
            name='trending',
        ),
        migrations.AddField(
            model_name='video',
            name='hotOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='trendingOrder',
            field=models.IntegerField(default=0),
        ),
    ]
