# Generated by Django 2.1.1 on 2018-11-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20181106_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user_id',
            new_name='user',
        ),
    ]
