# Generated by Django 2.1.3 on 2019-01-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190107_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='monetize',
            field=models.BooleanField(default=False),
        ),
    ]
