# Generated by Django 2.1.5 on 2019-01-14 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190114_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='hotOrder',
        ),
        migrations.RemoveField(
            model_name='video',
            name='trendingOrder',
        ),
        migrations.AddField(
            model_name='trendingvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trendingVideos', to='upload.Video'),
        ),
        migrations.AddField(
            model_name='hotvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotVideos', to='upload.Video'),
        ),
    ]
