# Generated by Django 2.1.5 on 2019-01-22 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190114_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='enable_comments',
            field=models.BooleanField(default=True, verbose_name='Enable comments'),
        ),
        migrations.AddField(
            model_name='video',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Publication date'),
            preserve_default=False,
        ),
    ]
