# Generated by Django 2.1.2 on 2018-11-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20181106_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='An apple a day keeps the doctor away', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
