# Generated by Django 2.1.2 on 2018-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20181115_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
