# Generated by Django 2.1.5 on 2019-01-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20190122_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='enable_comments',
        ),
        migrations.RemoveField(
            model_name='video',
            name='publication_date',
        ),
    ]
