# Generated by Django 2.1.2 on 2018-11-19 08:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_video_nsfw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
