# Generated by Django 2.1.4 on 2018-12-25 15:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20181119_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteemVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', django.contrib.postgres.fields.jsonb.JSONField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steemVideos', to='upload.Video')),
            ],
        ),
        migrations.CreateModel(
            name='WhaleShareVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', django.contrib.postgres.fields.jsonb.JSONField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whaleSharesVideo', to='upload.Video')),
            ],
        ),
    ]
