# Generated by Django 2.1.4 on 2018-12-29 02:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20181119_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permlink', models.CharField(blank=True, max_length=1024)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=5)),
                ('post_url', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SteemVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permlink', models.CharField(blank=True, max_length=1024)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=5)),
                ('post_url', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='WhaleShareVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permlink', models.CharField(blank=True, max_length=1024)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=5)),
                ('post_url', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=5),
        ),
        migrations.AddField(
            model_name='whalesharevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whaleVideos', to='upload.Video'),
        ),
        migrations.AddField(
            model_name='steemvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steemVideos', to='upload.Video'),
        ),
        migrations.AddField(
            model_name='smokevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smokeVideos', to='upload.Video'),
        ),
    ]
