# Generated by Django 2.1.3 on 2018-12-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20181229_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='total_earning',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='video',
            name='smoke',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='video',
            name='steem',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='video',
            name='whaleshares',
            field=models.FloatField(default=0.0),
        ),
    ]
