# Generated by Django 2.1.4 on 2019-01-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20181231_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[(1, 'English'), (2, 'Chinese'), (3, 'Spanish'), (4, 'German')], default='1', max_length=20),
        ),
    ]
