# Generated by Django 2.1.2 on 2018-11-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_dislike', '0002_activity_id_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id_unique',
        ),
    ]
